// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db_sqlc

import (
	"database/sql"
)

type Node struct {
	ID            int64
	Label         string
	BaseUrl       string
	IsOnline      bool
	LastHeartbeat sql.NullTime
}
