// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db_sqlc

import (
	"context"
	"database/sql"
)

const addNode = `-- name: AddNode :exec
INSERT INTO node (label, base_url, is_online)
    VALUES (?, ?, ?)
`

type AddNodeParams struct {
	Label    string
	BaseUrl  string
	IsOnline sql.NullBool
}

func (q *Queries) AddNode(ctx context.Context, arg AddNodeParams) error {
	_, err := q.db.ExecContext(ctx, addNode, arg.Label, arg.BaseUrl, arg.IsOnline)
	return err
}
